### ISSUE TITLE
Nokogiri Version causing error

### ISSUE THREAD

**Issue by KFad11** [learn-co-curriculum/phrg-oo-student-scraper#2]
In the Gemfile.lock, Nokogiri is specifying a version that is creating an error upon running 'bundle install' to start the lab. I needed to go in, delete lines 8 & 9 in the lock, then in the Gemfile itself delete the version it was specifying. @garettarrowood

**Comment by garettarrowood** [comment]
Nokogiri Changelog: https://nokogiri.org/CHANGELOG.html - For reference if most recent stable version does not work with README instructions.

**Comment by garettarrowood** [comment]
Resolved in https://github.com/learn-co-curriculum/phrg-oo-student-scraper/commit/3b332b3219e0f7c81055dcf4e405e02485a89bce
